### ISSUE TITLE
Can you make examples of what you support?

### ISSUE THREAD

**Issue by krux02** [Lompik/ob-nim#1]
I have seen tests, but they are _.el_ files. Could you add some _.org_  files as examples that show the features that you support. Some explanations of how things work for example passing tables from org to nim and how the result from nim is evaluated?

**Comment by Lompik** [comment]
See f957d12. 

Hope this helps.

**Comment by krux02** [comment]
Thanks a lot, things get a bit clearer now. I think this package could become quite helpful in the near future. I think I can close this issue for now.
